extension TranslationCatalog {
    static let portugueseBrazil: [L10nKey: String] =
        [
            .menuBarAppName: "Uso de IA",
            .notConfigured: "Não configurado",
            .unavailable: "Indisponível",
            .usagePanelTitle: "Uso de IA",
            .settingsTitle: "Ajustes",
            .lastUpdate: "Última atualização",
            .refreshNow: "Atualizar agora",
            .openSettings: "Ajustes",
            .staleData: "Dados desatualizados",
            .authenticationRequired: "Autenticação necessária",
            .authenticateInSettings: "Abra Ajustes para autenticar os provedores.",
            .generalSection: "Geral",
            .appearanceSection: "Aparência",
            .menuBarSection: "Barra de menus",
            .mainPanelSection: "Painel principal",
            .notificationsSection: "Notificações",
            .usageNotificationsSection: "Notificações de uso",
            .earlyResetNotificationsSection: "Notificações de redefinição antecipada",
            .language: "Idioma",
            .refreshInterval: "Intervalo de atualização",
            .usagePanelBackground: "Fundo do painel",
            .usagePanelBackgroundRegularMaterial: "Material",
            .usagePanelBackgroundSolidAdaptive: "Cor sólida",
            .codexMenuBarMetric: "Porcentagem do Codex na barra de menus",
            .claudeMenuBarMetric: "Porcentagem do Claude Code na barra de menus",
            .showCodexSparkUsage: "Mostrar uso do GPT-5.3-Codex-Spark",
            .menuBarMetricWeekly: "Uso semanal",
            .menuBarMetricFiveHour: "Uso de 5 horas",
            .menuBarIcons: "Ícones da barra de menus",
            .usagePanelProviders: "Provedores do painel de uso",
            .notificationsAhead: "Alertas de consumo adiantado",
            .notificationsBehind: "Alertas de consumo atrasado",
            .notificationsCodexReset: "Alertas de redefinição antecipada do Codex",
            .notificationsClaudeReset: "Alertas de redefinição antecipada do Claude Code",
            .providerCodex: "Codex",
            .providerClaude: "Claude Code",
            .providerCopilot: "GitHub Copilot",
            .enabled: "Ativado",
            .percentageShown: "Porcentagem exibida",
            .usageLimitFiveHourCodexSpark: "Limite de uso de 5 horas do GPT-5.3-Codex-Spark",
            .usageLimitWeeklyCodexSpark: "Limite de uso semanal do GPT-5.3-Codex-Spark",
            .usageLimitFiveHour: "Limite de uso de 5 horas",
            .usageLimitWeekly: "Limite de uso semanal",
            .usageLimitSevenDay: "Limite de uso de 7 dias",
            .usageLimitMonthly: "Limite de uso mensal",
            .usageMetricCredits: "Créditos",
            .resetAt: "Redefinição",
            .save: "Salvar",
            .cancel: "Cancelar",
            .signInToCodex: "Entrar no Codex",
            .signInToGitHubCopilot: "Entrar no GitHub",
            .copilotToken: "Token do GitHub Copilot",
            .fetchFailed: "Não foi possível buscar",
            .signedOut: "Sessão encerrada",
            .connected: "Conectado",
            .accountsSection: "Contas",
            .codexSessionHelp: "O Codex usa seu login local do Codex em `~/.codex/auth.json`. Se você usa o app de desktop, basta entrar nele e atualizar. Para o Codex CLI, execute `codex login` no Terminal.",
            .codexCliConnected: "Autenticação local do Codex detectada. Saia pelo Codex se quiser desconectá-la.",
            .claudeSessionHelp: "O Claude Code usa o login local do Claude Code no Keychain ou em `~/.claude/.credentials.json`. Execute `claude` no Terminal e depois atualize.",
            .claudeCliConnected: "Autenticação local do Claude Code detectada. Saia pelo Claude Code se quiser desconectá-la.",
            .copilotPatHelp: "O GitHub Copilot entra com o fluxo de dispositivo do GitHub e carrega o uso pela API do Copilot do GitHub.",
            .copilotDeviceFlowWaiting: "Continue no navegador e insira este código do GitHub: %@",
            .copilotDeviceFlowConnected: "O GitHub Copilot está conectado.",
            .saveAndRefresh: "Salvar e atualizar",
            .reload: "Recarregar",
            .tokenSaved: "Token salvo no Keychain.",
            .openCodexAndSignIn: "Abra o Codex e entre, depois clique em Salvar sessão.",
            .openGitHubCopilotAndSignIn: "Abra o GitHub, entre se necessário e clique em Salvar sessão.",
            .settingsTabAccounts: "Contas",
            .settingsTabDisplay: "Aparência",
            .settingsTabNotifications: "Notificações",
            .settingsTabLogs: "Logs",
            .settingsTabAbout: "Sobre",
            .providerStatusOk: "Conectado",
            .providerStatusNeedsAttention: "Precisa de atenção",
            .saveSession: "Salvar sessão",
            .copilotPlanHelp: "Entre com o GitHub para carregar seu uso do GitHub Copilot.",
            .copilotConnectedHelp: "O GitHub Copilot está conectado. Saia para remover o token do GitHub salvo.",
            .notificationsAheadDescription: "Avisa quando uma cota está sendo consumida mais rápido do que a janela de tempo sugere.",
            .notificationsBehindDescription: "Avisa quando a cota restante está claramente acima do esperado para o ponto atual da janela.",
            .notificationsCodexResetDescription: "Avisa quando a janela de 5 horas ou semanal do Codex parece redefinir antes do observado anteriormente.",
            .notificationsClaudeResetDescription: "Avisa quando a janela de 5 horas ou semanal do Claude Code parece redefinir antes do observado anteriormente.",
            .notificationTitleAheadFormat: "Adiantado no ritmo: %@",
            .notificationTitleBehindFormat: "Atrasado no ritmo: %@",
            .notificationBodyScheduleFormat: "O uso restante é %d%%, enquanto o cronograma sugere cerca de %d%%.",
            .notificationTitleCodexReset: "Redefinição antecipada do Codex detectada",
            .notificationTitleClaudeReset: "Redefinição antecipada do Claude Code detectada",
            .notificationBodyResetFormat: "%@ parece ter sido redefinido antes do esperado.",
            .notificationMetricFiveHourFormat: "Janela de 5 horas de %@",
            .notificationMetricWeeklyFormat: "Janela semanal de %@",
            .notificationMetricMonthlyFormat: "Cota mensal de %@",
            .notificationMetricCreditsFormat: "Créditos de %@",
            .copyLogs: "Copiar logs",
            .clearLogs: "Limpar logs",
            .noLogs: "Ainda não há logs",
            .logsCopied: "Logs copiados para a área de transferência.",
            .appVersion: "Versão",
            .projectSection: "Projeto",
            .projectRepository: "Repositório do GitHub",
            .reportIssue: "Relatar um problema",
            .legalSection: "Legal",
            .logoDisclaimer: "O logotipo da OpenAI, o logotipo da Claude e o logotipo do GitHub Copilot são usados apenas para identificar seus respectivos serviços. Todas as marcas comerciais, marcas de serviço e logotipos pertencem aos seus respectivos proprietários. Este app é independente e não é afiliado, endossado nem patrocinado pela OpenAI, Anthropic ou GitHub.",
            .quitApp: "Sair",
            .menuActionRefresh: "Atualizar",
            .menuActionSettings: "Ajustes",
            .signOut: "Sair",
            .noGitHubCopilotSessionFound: "Ainda não foram encontrados cookies de sessão do GitHub.",
            .noCodexSessionFound: "Ainda não foram encontrados cookies de sessão do ChatGPT.",
            .internetConnectionOffline: "Parece que a conexão com a internet está offline.",
        ]
}
