extension TranslationCatalog {
    static let english: [L10nKey: String] =
        [
            .menuBarAppName: "AI Usage",
            .notConfigured: "Not configured",
            .unavailable: "Unavailable",
            .usagePanelTitle: "AI Usage",
            .settingsTitle: "Settings",
            .lastUpdate: "Last update",
            .refreshNow: "Refresh now",
            .openSettings: "Settings",
            .staleData: "Stale data",
            .authenticationRequired: "Authentication required",
            .authenticateInSettings: "Open Settings to authenticate providers.",
            .generalSection: "General",
            .appearanceSection: "Appearance",
            .menuBarSection: "Menu bar",
            .mainPanelSection: "Main panel",
            .notificationsSection: "Notifications",
            .usageNotificationsSection: "Usage notifications",
            .earlyResetNotificationsSection: "Early reset notifications",
            .language: "Language",
            .refreshInterval: "Refresh interval",
            .usagePanelBackground: "Panel background",
            .usagePanelBackgroundRegularMaterial: "Material",
            .usagePanelBackgroundSolidAdaptive: "Solid color",
            .codexMenuBarMetric: "Codex menu bar percentage",
            .claudeMenuBarMetric: "Claude Code menu bar percentage",
            .showCodexSparkUsage: "Show GPT-5.3-Codex-Spark usage",
            .menuBarMetricWeekly: "Weekly usage",
            .menuBarMetricFiveHour: "5-hour usage",
            .menuBarIcons: "Menu bar icons",
            .usagePanelProviders: "Usage panel providers",
            .notificationsAhead: "Ahead-of-schedule alerts",
            .notificationsBehind: "Behind-schedule alerts",
            .notificationsCodexReset: "Codex early reset alerts",
            .notificationsClaudeReset: "Claude Code early reset alerts",
            .providerCodex: "Codex",
            .providerClaude: "Claude Code",
            .providerCopilot: "GitHub Copilot",
            .enabled: "Enabled",
            .percentageShown: "Percentage shown",
            .usageLimitFiveHourCodexSpark: "GPT-5.3-Codex-Spark 5-hour usage limit",
            .usageLimitWeeklyCodexSpark: "GPT-5.3-Codex-Spark weekly usage limit",
            .usageLimitFiveHour: "5-hour usage limit",
            .usageLimitWeekly: "Weekly usage limit",
            .usageLimitSevenDay: "7-day usage limit",
            .usageLimitMonthly: "Monthly usage limit",
            .usageMetricCredits: "Credits",
            .resetAt: "Reset",
            .save: "Save",
            .cancel: "Cancel",
            .signInToCodex: "Sign in to Codex",
            .signInToGitHubCopilot: "Sign in to GitHub",
            .copilotToken: "GitHub Copilot token",
            .fetchFailed: "Unable to fetch",
            .signedOut: "Signed out",
            .connected: "Connected",
            .accountsSection: "Accounts",
            .codexSessionHelp: "Codex uses your local Codex login from `~/.codex/auth.json`. If you use the desktop app, just sign in there and refresh. For Codex CLI, run `codex login` in Terminal.",
            .codexCliConnected: "Detected local Codex auth. Sign out through Codex if you want to disconnect it.",
            .claudeSessionHelp: "Claude Code uses the local Claude Code login from Keychain or `~/.claude/.credentials.json`. Run `claude` in Terminal, then refresh.",
            .claudeCliConnected: "Detected local Claude Code auth. Sign out through Claude Code if you want to disconnect it.",
            .copilotPatHelp: "GitHub Copilot signs in with GitHub device flow and loads usage from GitHub's Copilot API.",
            .copilotDeviceFlowWaiting: "Continue in your browser and enter this GitHub code: %@",
            .copilotDeviceFlowConnected: "GitHub Copilot is connected.",
            .saveAndRefresh: "Save and refresh",
            .reload: "Reload",
            .tokenSaved: "Token saved to Keychain.",
            .openCodexAndSignIn: "Open Codex and sign in, then click Save session.",
            .openGitHubCopilotAndSignIn: "Open GitHub, sign in if needed, then click Save session.",
            .settingsTabAccounts: "Accounts",
            .settingsTabDisplay: "Appearance",
            .settingsTabNotifications: "Notifications",
            .settingsTabLogs: "Logs",
            .settingsTabAbout: "About",
            .providerStatusOk: "Connected",
            .providerStatusNeedsAttention: "Needs attention",
            .saveSession: "Save session",
            .copilotPlanHelp: "Sign in with GitHub to load your GitHub Copilot usage.",
            .copilotConnectedHelp: "GitHub Copilot is connected. Sign out to remove the saved GitHub token.",
            .notificationsAheadDescription: "Warn when a quota is being consumed faster than the time window suggests.",
            .notificationsBehindDescription: "Warn when remaining quota is materially higher than expected for the current point in the window.",
            .notificationsCodexResetDescription: "Warn when the Codex 5-hour or weekly window appears to reset earlier than previously observed.",
            .notificationsClaudeResetDescription: "Warn when the Claude Code 5-hour or weekly window appears to reset earlier than previously observed.",
            .notificationTitleAheadFormat: "Ahead of schedule: %@",
            .notificationTitleBehindFormat: "Behind schedule: %@",
            .notificationBodyScheduleFormat: "Remaining usage is %d%% while the schedule suggests about %d%% should remain.",
            .notificationTitleCodexReset: "Codex reset detected early",
            .notificationTitleClaudeReset: "Claude Code reset detected early",
            .notificationBodyResetFormat: "%@ appears to have reset earlier than expected.",
            .notificationMetricFiveHourFormat: "%@ 5-hour window",
            .notificationMetricWeeklyFormat: "%@ weekly window",
            .notificationMetricMonthlyFormat: "%@ monthly quota",
            .notificationMetricCreditsFormat: "%@ credits",
            .copyLogs: "Copy logs",
            .clearLogs: "Clear logs",
            .noLogs: "No logs yet",
            .logsCopied: "Logs copied to the clipboard.",
            .appVersion: "Version",
            .projectSection: "Project",
            .projectRepository: "GitHub repository",
            .reportIssue: "Report an issue",
            .legalSection: "Legal",
            .logoDisclaimer: "The OpenAI logo, Claude logo, and GitHub Copilot logo are used only to identify their respective services. All trademarks, service marks, and logos are the property of their respective owners. This app is independent and is not affiliated with, endorsed by, or sponsored by OpenAI, Anthropic, or GitHub.",
            .quitApp: "Quit",
            .menuActionRefresh: "Refresh",
            .menuActionSettings: "Settings",
            .signOut: "Sign out",
            .noGitHubCopilotSessionFound: "No GitHub session cookies were found yet.",
            .noCodexSessionFound: "No ChatGPT session cookies were found yet.",
            .internetConnectionOffline: "The internet connection appears to be offline.",
        ]
}
