extension TranslationCatalog {
    static let polish: [L10nKey: String] =
        [
            .menuBarAppName: "Użycie AI",
            .notConfigured: "Nie skonfigurowano",
            .unavailable: "Niedostępne",
            .usagePanelTitle: "Użycie AI",
            .settingsTitle: "Ustawienia",
            .lastUpdate: "Ostatnia aktualizacja",
            .refreshNow: "Odśwież teraz",
            .openSettings: "Ustawienia",
            .staleData: "Nieaktualne dane",
            .authenticationRequired: "Wymagana autoryzacja",
            .authenticateInSettings: "Otwórz Ustawienia, aby skonfigurować dostęp do usług.",
            .generalSection: "Ogólne",
            .appearanceSection: "Wygląd",
            .menuBarSection: "Pasek menu",
            .mainPanelSection: "Panel główny",
            .notificationsSection: "Powiadomienia",
            .usageNotificationsSection: "Powiadomienia o użyciu",
            .earlyResetNotificationsSection: "Powiadomienia o wczesnym resecie",
            .language: "Język",
            .refreshInterval: "Częstotliwość odświeżania",
            .usagePanelBackground: "Tło panelu",
            .usagePanelBackgroundRegularMaterial: "Materiał",
            .usagePanelBackgroundSolidAdaptive: "Jednolity kolor",
            .codexMenuBarMetric: "Procent Codex na pasku menu",
            .claudeMenuBarMetric: "Procent Claude Code na pasku menu",
            .showCodexSparkUsage: "Pokaż użycie GPT-5.3-Codex-Spark",
            .menuBarMetricWeekly: "Użycie tygodniowe",
            .menuBarMetricFiveHour: "Użycie 5-godzinne",
            .menuBarIcons: "Ikony na pasku menu",
            .usagePanelProviders: "Usługi w panelu",
            .notificationsAhead: "Alerty: za szybkie zużycie",
            .notificationsBehind: "Alerty: zbyt wolne zużycie",
            .notificationsCodexReset: "Alerty o wczesnym resecie Codex",
            .notificationsClaudeReset: "Alerty o wczesnym resecie Claude Code",
            .providerCodex: "Codex",
            .providerClaude: "Claude Code",
            .providerCopilot: "GitHub Copilot",
            .enabled: "Włączone",
            .percentageShown: "Pokazywany procent",
            .usageLimitFiveHourCodexSpark: "5-godzinny limit wykorzystania GPT-5.3-Codex-Spark",
            .usageLimitWeeklyCodexSpark: "Tygodniowy limit wykorzystania GPT-5.3-Codex-Spark",
            .usageLimitFiveHour: "5-godzinny limit wykorzystania",
            .usageLimitWeekly: "Tygodniowy limit wykorzystania",
            .usageLimitSevenDay: "7-dniowy limit wykorzystania",
            .usageLimitMonthly: "Miesięczny limit wykorzystania",
            .usageMetricCredits: "Kredyty",
            .resetAt: "Reset",
            .save: "Zapisz",
            .cancel: "Anuluj",
            .signInToCodex: "Zaloguj do Codex",
            .signInToGitHubCopilot: "Zaloguj do GitHub",
            .copilotToken: "Token GitHub Copilot",
            .fetchFailed: "Nie udało się pobrać danych",
            .signedOut: "Wylogowano",
            .connected: "Połączono",
            .accountsSection: "Konta",
            .codexSessionHelp: "Codex korzysta z lokalnego logowania Codex z `~/.codex/auth.json`. Jeśli używasz aplikacji desktopowej, po prostu zaloguj się w niej i odśwież. W Codex CLI uruchom `codex login` w Terminalu.",
            .codexCliConnected: "Wykryto lokalne uwierzytelnienie Codex. Wyloguj się z poziomu Codex, jeśli chcesz je odłączyć.",
            .claudeSessionHelp: "Claude Code korzysta z lokalnego logowania Claude Code z Keychain lub `~/.claude/.credentials.json`. Uruchom `claude` w Terminalu, a potem odśwież.",
            .claudeCliConnected: "Wykryto lokalne uwierzytelnienie Claude Code. Wyloguj się z poziomu Claude Code, jeśli chcesz je odłączyć.",
            .copilotPatHelp: "GitHub Copilot loguje się przez GitHub device flow i pobiera użycie z API Copilot w GitHub.",
            .copilotDeviceFlowWaiting: "Kontynuuj w przeglądarce i wpisz ten kod GitHub: %@",
            .copilotDeviceFlowConnected: "GitHub Copilot jest połączony.",
            .saveAndRefresh: "Zapisz i odśwież",
            .reload: "Przeładuj",
            .tokenSaved: "Token zapisany w Keychain.",
            .openCodexAndSignIn: "Otwórz Codex i zaloguj się, a potem kliknij Zapisz sesję.",
            .openGitHubCopilotAndSignIn: "Otwórz GitHub, zaloguj się w razie potrzeby, a potem kliknij Zapisz sesję.",
            .settingsTabAccounts: "Konta",
            .settingsTabDisplay: "Wygląd",
            .settingsTabNotifications: "Powiadomienia",
            .settingsTabLogs: "Logi",
            .settingsTabAbout: "Informacje",
            .providerStatusOk: "Połączono",
            .providerStatusNeedsAttention: "Wymaga uwagi",
            .saveSession: "Zapisz sesję",
            .copilotPlanHelp: "Zaloguj się do GitHub, aby wczytać użycie GitHub Copilot.",
            .copilotConnectedHelp: "GitHub Copilot jest połączony. Wyloguj się, aby usunąć zapisany token GitHub.",
            .notificationsAheadDescription: "Ostrzegaj, gdy limit jest zużywany szybciej, niż wynikałoby z upływu okna czasowego.",
            .notificationsBehindDescription: "Ostrzegaj, gdy pozostały limit jest wyraźnie wyższy niż oczekiwany w bieżącym momencie okna czasowego.",
            .notificationsCodexResetDescription: "Ostrzegaj, gdy okno 5-godzinne lub tygodniowe Codex wygląda na zresetowane wcześniej niż poprzednio.",
            .notificationsClaudeResetDescription: "Ostrzegaj, gdy okno 5-godzinne lub tygodniowe Claude Code wygląda na zresetowane wcześniej niż poprzednio.",
            .notificationTitleAheadFormat: "Zużycie powyżej tempa: %@",
            .notificationTitleBehindFormat: "Zużycie poniżej tempa: %@",
            .notificationBodyScheduleFormat: "Pozostałe użycie to %d%%, a harmonogram sugeruje około %d%%.",
            .notificationTitleCodexReset: "Wykryto wcześniejszy reset Codex",
            .notificationTitleClaudeReset: "Wykryto wcześniejszy reset Claude Code",
            .notificationBodyResetFormat: "%@ wygląda na zresetowane wcześniej niż oczekiwano.",
            .notificationMetricFiveHourFormat: "5-godzinne okno %@",
            .notificationMetricWeeklyFormat: "Tygodniowe okno %@",
            .notificationMetricMonthlyFormat: "Miesięczny limit %@",
            .notificationMetricCreditsFormat: "Kredyty %@",
            .copyLogs: "Kopiuj logi",
            .clearLogs: "Wyczyść logi",
            .noLogs: "Brak logów",
            .logsCopied: "Logi skopiowano do schowka.",
            .appVersion: "Wersja",
            .projectSection: "Projekt",
            .projectRepository: "Repozytorium GitHub",
            .reportIssue: "Zgłoś problem",
            .legalSection: "Informacje prawne",
            .logoDisclaimer: "Logo OpenAI, logo Claude i logo GitHub Copilot są używane wyłącznie w celu identyfikacji odpowiednich usług. Wszystkie znaki towarowe, znaki usługowe i logo należą do ich właścicieli. Ta aplikacja jest niezależna i nie jest powiązana z OpenAI, Anthropic ani GitHub, ani przez nie sponsorowana lub rekomendowana.",
            .quitApp: "Zakończ",
            .menuActionRefresh: "Odśwież",
            .menuActionSettings: "Ustawienia",
            .signOut: "Wyloguj się",
            .noGitHubCopilotSessionFound: "Nie znaleziono jeszcze ciasteczek sesji GitHub.",
            .noCodexSessionFound: "Nie znaleziono jeszcze ciasteczek sesji ChatGPT.",
            .internetConnectionOffline: "Wygląda na to, że połączenie z internetem jest offline.",
        ]
}
