extension TranslationCatalog {
    static let spanish: [L10nKey: String] =
        [
            .menuBarAppName: "Uso de IA",
            .notConfigured: "No configurado",
            .unavailable: "No disponible",
            .usagePanelTitle: "Uso de IA",
            .settingsTitle: "Ajustes",
            .lastUpdate: "Última actualización",
            .refreshNow: "Actualizar ahora",
            .openSettings: "Ajustes",
            .staleData: "Datos obsoletos",
            .authenticationRequired: "Autenticación requerida",
            .authenticateInSettings: "Abre Ajustes para autenticar los proveedores.",
            .generalSection: "General",
            .appearanceSection: "Apariencia",
            .menuBarSection: "Barra de menús",
            .mainPanelSection: "Panel principal",
            .notificationsSection: "Notificaciones",
            .usageNotificationsSection: "Notificaciones de uso",
            .earlyResetNotificationsSection: "Notificaciones de reinicio anticipado",
            .language: "Idioma",
            .refreshInterval: "Intervalo de actualización",
            .usagePanelBackground: "Fondo del panel",
            .usagePanelBackgroundRegularMaterial: "Material",
            .usagePanelBackgroundSolidAdaptive: "Color sólido",
            .codexMenuBarMetric: "Porcentaje de Codex en la barra de menús",
            .claudeMenuBarMetric: "Porcentaje de Claude Code en la barra de menús",
            .showCodexSparkUsage: "Mostrar uso de GPT-5.3-Codex-Spark",
            .menuBarMetricWeekly: "Uso semanal",
            .menuBarMetricFiveHour: "Uso de 5 horas",
            .menuBarIcons: "Iconos de la barra de menús",
            .usagePanelProviders: "Proveedores del panel de uso",
            .notificationsAhead: "Alertas de consumo adelantado",
            .notificationsBehind: "Alertas de consumo retrasado",
            .notificationsCodexReset: "Alertas de reinicio anticipado de Codex",
            .notificationsClaudeReset: "Alertas de reinicio anticipado de Claude Code",
            .providerCodex: "Codex",
            .providerClaude: "Claude Code",
            .providerCopilot: "GitHub Copilot",
            .enabled: "Activado",
            .percentageShown: "Porcentaje mostrado",
            .usageLimitFiveHourCodexSpark: "Límite de uso de 5 horas de GPT-5.3-Codex-Spark",
            .usageLimitWeeklyCodexSpark: "Límite de uso semanal de GPT-5.3-Codex-Spark",
            .usageLimitFiveHour: "Límite de uso de 5 horas",
            .usageLimitWeekly: "Límite de uso semanal",
            .usageLimitSevenDay: "Límite de uso de 7 días",
            .usageLimitMonthly: "Límite de uso mensual",
            .usageMetricCredits: "Créditos",
            .resetAt: "Reinicio",
            .save: "Guardar",
            .cancel: "Cancelar",
            .signInToCodex: "Iniciar sesión en Codex",
            .signInToGitHubCopilot: "Iniciar sesión en GitHub",
            .copilotToken: "Token de GitHub Copilot",
            .fetchFailed: "No se pudo obtener",
            .signedOut: "Sesión cerrada",
            .connected: "Conectado",
            .accountsSection: "Cuentas",
            .codexSessionHelp: "Codex usa tu inicio de sesión local de Codex desde `~/.codex/auth.json`. Si usas la app de escritorio, inicia sesión allí y actualiza. Para Codex CLI, ejecuta `codex login` en Terminal.",
            .codexCliConnected: "Se detectó autenticación local de Codex. Cierra sesión en Codex si quieres desconectarla.",
            .claudeSessionHelp: "Claude Code usa el inicio de sesión local de Claude Code desde Keychain o `~/.claude/.credentials.json`. Ejecuta `claude` en Terminal y luego actualiza.",
            .claudeCliConnected: "Se detectó autenticación local de Claude Code. Cierra sesión en Claude Code si quieres desconectarla.",
            .copilotPatHelp: "GitHub Copilot inicia sesión con el flujo de dispositivo de GitHub y carga el uso desde la API de Copilot de GitHub.",
            .copilotDeviceFlowWaiting: "Continúa en tu navegador e introduce este código de GitHub: %@",
            .copilotDeviceFlowConnected: "GitHub Copilot está conectado.",
            .saveAndRefresh: "Guardar y actualizar",
            .reload: "Recargar",
            .tokenSaved: "Token guardado en Keychain.",
            .openCodexAndSignIn: "Abre Codex e inicia sesión, luego haz clic en Guardar sesión.",
            .openGitHubCopilotAndSignIn: "Abre GitHub, inicia sesión si hace falta, luego haz clic en Guardar sesión.",
            .settingsTabAccounts: "Cuentas",
            .settingsTabDisplay: "Apariencia",
            .settingsTabNotifications: "Notificaciones",
            .settingsTabLogs: "Registros",
            .settingsTabAbout: "Acerca de",
            .providerStatusOk: "Conectado",
            .providerStatusNeedsAttention: "Requiere atención",
            .saveSession: "Guardar sesión",
            .copilotPlanHelp: "Inicia sesión con GitHub para cargar tu uso de GitHub Copilot.",
            .copilotConnectedHelp: "GitHub Copilot está conectado. Cierra sesión para eliminar el token de GitHub guardado.",
            .notificationsAheadDescription: "Avisa cuando una cuota se consume más rápido de lo que sugiere la ventana temporal.",
            .notificationsBehindDescription: "Avisa cuando la cuota restante es claramente mayor de lo esperado para el punto actual de la ventana.",
            .notificationsCodexResetDescription: "Avisa cuando la ventana de 5 horas o semanal de Codex parece reiniciarse antes de lo observado anteriormente.",
            .notificationsClaudeResetDescription: "Avisa cuando la ventana de 5 horas o semanal de Claude Code parece reiniciarse antes de lo observado anteriormente.",
            .notificationTitleAheadFormat: "Por delante del ritmo: %@",
            .notificationTitleBehindFormat: "Por detrás del ritmo: %@",
            .notificationBodyScheduleFormat: "Queda un %d%% de uso, mientras que el calendario sugiere que debería quedar alrededor de un %d%%.",
            .notificationTitleCodexReset: "Reinicio anticipado de Codex detectado",
            .notificationTitleClaudeReset: "Reinicio anticipado de Claude Code detectado",
            .notificationBodyResetFormat: "%@ parece haberse reiniciado antes de lo esperado.",
            .notificationMetricFiveHourFormat: "Ventana de 5 horas de %@",
            .notificationMetricWeeklyFormat: "Ventana semanal de %@",
            .notificationMetricMonthlyFormat: "Cuota mensual de %@",
            .notificationMetricCreditsFormat: "Créditos de %@",
            .copyLogs: "Copiar registros",
            .clearLogs: "Borrar registros",
            .noLogs: "Aún no hay registros",
            .logsCopied: "Registros copiados al portapapeles.",
            .appVersion: "Versión",
            .projectSection: "Proyecto",
            .projectRepository: "Repositorio de GitHub",
            .reportIssue: "Informar de un problema",
            .legalSection: "Legal",
            .logoDisclaimer: "El logotipo de OpenAI, el logotipo de Claude y el logotipo de GitHub Copilot se usan solo para identificar sus respectivos servicios. Todas las marcas comerciales, marcas de servicio y logotipos pertenecen a sus respectivos propietarios. Esta app es independiente y no está afiliada, avalada ni patrocinada por OpenAI, Anthropic o GitHub.",
            .quitApp: "Salir",
            .menuActionRefresh: "Actualizar",
            .menuActionSettings: "Ajustes",
            .signOut: "Cerrar sesión",
            .noGitHubCopilotSessionFound: "Aún no se encontraron cookies de sesión de GitHub.",
            .noCodexSessionFound: "Aún no se encontraron cookies de sesión de ChatGPT.",
            .internetConnectionOffline: "Parece que la conexión a internet está sin conexión.",
        ]
}
