extension TranslationCatalog {
    static let french: [L10nKey: String] =
        [
            .menuBarAppName: "Utilisation de l'IA",
            .notConfigured: "Non configuré",
            .unavailable: "Indisponible",
            .usagePanelTitle: "Utilisation de l'IA",
            .settingsTitle: "Réglages",
            .lastUpdate: "Dernière mise à jour",
            .refreshNow: "Actualiser maintenant",
            .openSettings: "Réglages",
            .staleData: "Données obsolètes",
            .authenticationRequired: "Authentification requise",
            .authenticateInSettings: "Ouvrez Réglages pour authentifier les fournisseurs.",
            .generalSection: "Général",
            .appearanceSection: "Apparence",
            .menuBarSection: "Barre des menus",
            .mainPanelSection: "Panneau principal",
            .notificationsSection: "Notifications",
            .usageNotificationsSection: "Notifications d'utilisation",
            .earlyResetNotificationsSection: "Notifications de réinitialisation anticipée",
            .language: "Langue",
            .refreshInterval: "Intervalle d'actualisation",
            .usagePanelBackground: "Arrière-plan du panneau",
            .usagePanelBackgroundRegularMaterial: "Matériau",
            .usagePanelBackgroundSolidAdaptive: "Couleur unie",
            .codexMenuBarMetric: "Pourcentage Codex dans la barre des menus",
            .claudeMenuBarMetric: "Pourcentage Claude Code dans la barre des menus",
            .showCodexSparkUsage: "Afficher l'utilisation de GPT-5.3-Codex-Spark",
            .menuBarMetricWeekly: "Utilisation hebdomadaire",
            .menuBarMetricFiveHour: "Utilisation sur 5 heures",
            .menuBarIcons: "Icônes de la barre des menus",
            .usagePanelProviders: "Fournisseurs du panneau d'utilisation",
            .notificationsAhead: "Alertes d'avance sur le rythme",
            .notificationsBehind: "Alertes de retard sur le rythme",
            .notificationsCodexReset: "Alertes de réinitialisation anticipée de Codex",
            .notificationsClaudeReset: "Alertes de réinitialisation anticipée de Claude Code",
            .providerCodex: "Codex",
            .providerClaude: "Claude Code",
            .providerCopilot: "GitHub Copilot",
            .enabled: "Activé",
            .percentageShown: "Pourcentage affiché",
            .usageLimitFiveHourCodexSpark: "Limite d'utilisation GPT-5.3-Codex-Spark sur 5 heures",
            .usageLimitWeeklyCodexSpark: "Limite d'utilisation hebdomadaire GPT-5.3-Codex-Spark",
            .usageLimitFiveHour: "Limite d'utilisation sur 5 heures",
            .usageLimitWeekly: "Limite d'utilisation hebdomadaire",
            .usageLimitSevenDay: "Limite d'utilisation sur 7 jours",
            .usageLimitMonthly: "Limite d'utilisation mensuelle",
            .usageMetricCredits: "Crédits",
            .resetAt: "Réinitialisation",
            .save: "Enregistrer",
            .cancel: "Annuler",
            .signInToCodex: "Se connecter à Codex",
            .signInToGitHubCopilot: "Se connecter à GitHub",
            .copilotToken: "Jeton GitHub Copilot",
            .fetchFailed: "Impossible de récupérer les données",
            .signedOut: "Déconnecté",
            .connected: "Connecté",
            .accountsSection: "Comptes",
            .codexSessionHelp: "Codex utilise votre connexion Codex locale depuis `~/.codex/auth.json`. Si vous utilisez l'app de bureau, connectez-vous simplement là-bas puis actualisez. Pour Codex CLI, exécutez `codex login` dans Terminal.",
            .codexCliConnected: "Authentification Codex locale détectée. Déconnectez-vous via Codex si vous voulez la supprimer.",
            .claudeSessionHelp: "Claude Code utilise la connexion Claude Code locale depuis Keychain ou `~/.claude/.credentials.json`. Exécutez `claude` dans Terminal, puis actualisez.",
            .claudeCliConnected: "Authentification Claude Code locale détectée. Déconnectez-vous via Claude Code si vous voulez la supprimer.",
            .copilotPatHelp: "GitHub Copilot se connecte avec le flux d'appareil GitHub et charge l'utilisation depuis l'API Copilot de GitHub.",
            .copilotDeviceFlowWaiting: "Continuez dans votre navigateur et saisissez ce code GitHub : %@",
            .copilotDeviceFlowConnected: "GitHub Copilot est connecté.",
            .saveAndRefresh: "Enregistrer et actualiser",
            .reload: "Recharger",
            .tokenSaved: "Jeton enregistré dans Keychain.",
            .openCodexAndSignIn: "Ouvrez Codex et connectez-vous, puis cliquez sur Enregistrer la session.",
            .openGitHubCopilotAndSignIn: "Ouvrez GitHub, connectez-vous si nécessaire, puis cliquez sur Enregistrer la session.",
            .settingsTabAccounts: "Comptes",
            .settingsTabDisplay: "Apparence",
            .settingsTabNotifications: "Notifications",
            .settingsTabLogs: "Journaux",
            .settingsTabAbout: "À propos",
            .providerStatusOk: "Connecté",
            .providerStatusNeedsAttention: "Nécessite une attention",
            .saveSession: "Enregistrer la session",
            .copilotPlanHelp: "Connectez-vous avec GitHub pour charger votre utilisation de GitHub Copilot.",
            .copilotConnectedHelp: "GitHub Copilot est connecté. Déconnectez-vous pour supprimer le jeton GitHub enregistré.",
            .notificationsAheadDescription: "Avertit lorsqu'un quota est consommé plus vite que ne le suggère la fenêtre de temps.",
            .notificationsBehindDescription: "Avertit lorsque le quota restant est nettement supérieur à ce qui est attendu à ce point de la fenêtre.",
            .notificationsCodexResetDescription: "Avertit lorsque la fenêtre Codex de 5 heures ou hebdomadaire semble se réinitialiser plus tôt qu'observé précédemment.",
            .notificationsClaudeResetDescription: "Avertit lorsque la fenêtre Claude Code de 5 heures ou hebdomadaire semble se réinitialiser plus tôt qu'observé précédemment.",
            .notificationTitleAheadFormat: "En avance sur le rythme : %@",
            .notificationTitleBehindFormat: "En retard sur le rythme : %@",
            .notificationBodyScheduleFormat: "L'utilisation restante est de %d%%, tandis que le calendrier suggère environ %d%%.",
            .notificationTitleCodexReset: "Réinitialisation anticipée de Codex détectée",
            .notificationTitleClaudeReset: "Réinitialisation anticipée de Claude Code détectée",
            .notificationBodyResetFormat: "%@ semble s'être réinitialisé plus tôt que prévu.",
            .notificationMetricFiveHourFormat: "Fenêtre de 5 heures de %@",
            .notificationMetricWeeklyFormat: "Fenêtre hebdomadaire de %@",
            .notificationMetricMonthlyFormat: "Quota mensuel de %@",
            .notificationMetricCreditsFormat: "Crédits de %@",
            .copyLogs: "Copier les journaux",
            .clearLogs: "Effacer les journaux",
            .noLogs: "Aucun journal pour le moment",
            .logsCopied: "Journaux copiés dans le presse-papiers.",
            .appVersion: "Version",
            .projectSection: "Projet",
            .projectRepository: "Dépôt GitHub",
            .reportIssue: "Signaler un problème",
            .legalSection: "Mentions légales",
            .logoDisclaimer: "Le logo OpenAI, le logo Claude et le logo GitHub Copilot sont utilisés uniquement pour identifier leurs services respectifs. Toutes les marques, marques de service et logos appartiennent à leurs propriétaires respectifs. Cette app est indépendante et n'est ni affiliée, ni approuvée, ni sponsorisée par OpenAI, Anthropic ou GitHub.",
            .quitApp: "Quitter",
            .menuActionRefresh: "Actualiser",
            .menuActionSettings: "Réglages",
            .signOut: "Se déconnecter",
            .noGitHubCopilotSessionFound: "Aucun cookie de session GitHub n'a encore été trouvé.",
            .noCodexSessionFound: "Aucun cookie de session ChatGPT n'a encore été trouvé.",
            .internetConnectionOffline: "La connexion à internet semble être hors ligne.",
        ]
}
