extension TranslationCatalog {
    static let japanese: [L10nKey: String] =
        [
            .menuBarAppName: "AI使用量",
            .notConfigured: "未設定",
            .unavailable: "利用不可",
            .usagePanelTitle: "AI使用量",
            .settingsTitle: "設定",
            .lastUpdate: "最終更新",
            .refreshNow: "今すぐ更新",
            .openSettings: "設定",
            .staleData: "古いデータ",
            .authenticationRequired: "認証が必要です",
            .authenticateInSettings: "設定を開いてプロバイダーを認証してください。",
            .generalSection: "一般",
            .appearanceSection: "外観",
            .menuBarSection: "メニューバー",
            .mainPanelSection: "メインパネル",
            .notificationsSection: "通知",
            .usageNotificationsSection: "使用量通知",
            .earlyResetNotificationsSection: "早期リセット通知",
            .language: "言語",
            .refreshInterval: "更新間隔",
            .usagePanelBackground: "パネル背景",
            .usagePanelBackgroundRegularMaterial: "マテリアル",
            .usagePanelBackgroundSolidAdaptive: "単色",
            .codexMenuBarMetric: "メニューバーのCodex割合",
            .claudeMenuBarMetric: "メニューバーのClaude Code割合",
            .showCodexSparkUsage: "GPT-5.3-Codex-Sparkの使用量を表示",
            .menuBarMetricWeekly: "週間使用量",
            .menuBarMetricFiveHour: "5時間使用量",
            .menuBarIcons: "メニューバーアイコン",
            .usagePanelProviders: "使用量パネルのプロバイダー",
            .notificationsAhead: "予定より速い消費のアラート",
            .notificationsBehind: "予定より遅い消費のアラート",
            .notificationsCodexReset: "Codexの早期リセットアラート",
            .notificationsClaudeReset: "Claude Codeの早期リセットアラート",
            .providerCodex: "Codex",
            .providerClaude: "Claude Code",
            .providerCopilot: "GitHub Copilot",
            .enabled: "有効",
            .percentageShown: "表示する割合",
            .usageLimitFiveHourCodexSpark: "GPT-5.3-Codex-Sparkの5時間使用上限",
            .usageLimitWeeklyCodexSpark: "GPT-5.3-Codex-Sparkの週間使用上限",
            .usageLimitFiveHour: "5時間使用上限",
            .usageLimitWeekly: "週間使用上限",
            .usageLimitSevenDay: "7日間使用上限",
            .usageLimitMonthly: "月間使用上限",
            .usageMetricCredits: "クレジット",
            .resetAt: "リセット",
            .save: "保存",
            .cancel: "キャンセル",
            .signInToCodex: "Codexにサインイン",
            .signInToGitHubCopilot: "GitHubにサインイン",
            .copilotToken: "GitHub Copilotトークン",
            .fetchFailed: "取得できません",
            .signedOut: "サインアウト済み",
            .connected: "接続済み",
            .accountsSection: "アカウント",
            .codexSessionHelp: "Codexは`~/.codex/auth.json`のローカルCodexログインを使用します。デスクトップアプリを使っている場合は、そこでサインインして更新してください。Codex CLIでは、Terminalで`codex login`を実行してください。",
            .codexCliConnected: "ローカルのCodex認証を検出しました。切断するにはCodex側でサインアウトしてください。",
            .claudeSessionHelp: "Claude CodeはKeychainまたは`~/.claude/.credentials.json`のローカルClaude Codeログインを使用します。Terminalで`claude`を実行してから更新してください。",
            .claudeCliConnected: "ローカルのClaude Code認証を検出しました。切断するにはClaude Code側でサインアウトしてください。",
            .copilotPatHelp: "GitHub CopilotはGitHubのデバイスフローでサインインし、GitHubのCopilot APIから使用量を読み込みます。",
            .copilotDeviceFlowWaiting: "ブラウザで続行し、このGitHubコードを入力してください: %@",
            .copilotDeviceFlowConnected: "GitHub Copilotは接続済みです。",
            .saveAndRefresh: "保存して更新",
            .reload: "再読み込み",
            .tokenSaved: "トークンをKeychainに保存しました。",
            .openCodexAndSignIn: "Codexを開いてサインインし、セッションを保存をクリックしてください。",
            .openGitHubCopilotAndSignIn: "GitHubを開き、必要ならサインインしてからセッションを保存をクリックしてください。",
            .settingsTabAccounts: "アカウント",
            .settingsTabDisplay: "外観",
            .settingsTabNotifications: "通知",
            .settingsTabLogs: "ログ",
            .settingsTabAbout: "情報",
            .providerStatusOk: "接続済み",
            .providerStatusNeedsAttention: "確認が必要",
            .saveSession: "セッションを保存",
            .copilotPlanHelp: "GitHubでサインインしてGitHub Copilotの使用量を読み込みます。",
            .copilotConnectedHelp: "GitHub Copilotは接続済みです。保存されたGitHubトークンを削除するにはサインアウトしてください。",
            .notificationsAheadDescription: "時間枠から見込まれるよりも速くクォータが消費されている場合に警告します。",
            .notificationsBehindDescription: "現在の時間枠で期待されるよりも残りクォータが明らかに多い場合に警告します。",
            .notificationsCodexResetDescription: "Codexの5時間または週間ウィンドウが、以前の観測より早くリセットされたように見える場合に警告します。",
            .notificationsClaudeResetDescription: "Claude Codeの5時間または週間ウィンドウが、以前の観測より早くリセットされたように見える場合に警告します。",
            .notificationTitleAheadFormat: "予定より速い消費: %@",
            .notificationTitleBehindFormat: "予定より遅い消費: %@",
            .notificationBodyScheduleFormat: "残り使用量は%d%%ですが、予定では約%d%%残っているはずです。",
            .notificationTitleCodexReset: "Codexの早期リセットを検出",
            .notificationTitleClaudeReset: "Claude Codeの早期リセットを検出",
            .notificationBodyResetFormat: "%@は予想より早くリセットされたようです。",
            .notificationMetricFiveHourFormat: "%@の5時間ウィンドウ",
            .notificationMetricWeeklyFormat: "%@の週間ウィンドウ",
            .notificationMetricMonthlyFormat: "%@の月間クォータ",
            .notificationMetricCreditsFormat: "%@のクレジット",
            .copyLogs: "ログをコピー",
            .clearLogs: "ログを消去",
            .noLogs: "ログはまだありません",
            .logsCopied: "ログをクリップボードにコピーしました。",
            .appVersion: "バージョン",
            .projectSection: "プロジェクト",
            .projectRepository: "GitHubリポジトリ",
            .reportIssue: "問題を報告",
            .legalSection: "法的情報",
            .logoDisclaimer: "OpenAIロゴ、Claudeロゴ、GitHub Copilotロゴは、それぞれのサービスを識別する目的でのみ使用されています。すべての商標、サービスマーク、ロゴは各所有者に帰属します。このアプリは独立したものであり、OpenAI、Anthropic、GitHubと提携、承認、または後援されていません。",
            .quitApp: "終了",
            .menuActionRefresh: "更新",
            .menuActionSettings: "設定",
            .signOut: "サインアウト",
            .noGitHubCopilotSessionFound: "GitHubのセッションCookieはまだ見つかっていません。",
            .noCodexSessionFound: "ChatGPTのセッションCookieはまだ見つかっていません。",
            .internetConnectionOffline: "インターネット接続がオフラインのようです。",
        ]
}
