extension TranslationCatalog {
    static let german: [L10nKey: String] =
        [
            .menuBarAppName: "KI-Nutzung",
            .notConfigured: "Nicht konfiguriert",
            .unavailable: "Nicht verfügbar",
            .usagePanelTitle: "KI-Nutzung",
            .settingsTitle: "Einstellungen",
            .lastUpdate: "Letzte Aktualisierung",
            .refreshNow: "Jetzt aktualisieren",
            .openSettings: "Einstellungen",
            .staleData: "Veraltete Daten",
            .authenticationRequired: "Authentifizierung erforderlich",
            .authenticateInSettings: "Öffne die Einstellungen, um Anbieter zu authentifizieren.",
            .generalSection: "Allgemein",
            .appearanceSection: "Darstellung",
            .menuBarSection: "Menüleiste",
            .mainPanelSection: "Hauptpanel",
            .notificationsSection: "Mitteilungen",
            .usageNotificationsSection: "Nutzungsmitteilungen",
            .earlyResetNotificationsSection: "Mitteilungen zu frühem Zurücksetzen",
            .language: "Sprache",
            .refreshInterval: "Aktualisierungsintervall",
            .usagePanelBackground: "Panel-Hintergrund",
            .usagePanelBackgroundRegularMaterial: "Material",
            .usagePanelBackgroundSolidAdaptive: "Einfarbig",
            .codexMenuBarMetric: "Codex-Prozentwert in der Menüleiste",
            .claudeMenuBarMetric: "Claude-Code-Prozentwert in der Menüleiste",
            .showCodexSparkUsage: "GPT-5.3-Codex-Spark-Nutzung anzeigen",
            .menuBarMetricWeekly: "Wöchentliche Nutzung",
            .menuBarMetricFiveHour: "5-Stunden-Nutzung",
            .menuBarIcons: "Menüleistensymbole",
            .usagePanelProviders: "Anbieter im Nutzungspanel",
            .notificationsAhead: "Warnungen bei zu schnellem Verbrauch",
            .notificationsBehind: "Warnungen bei zu langsamem Verbrauch",
            .notificationsCodexReset: "Codex-Warnungen zu frühem Zurücksetzen",
            .notificationsClaudeReset: "Claude-Code-Warnungen zu frühem Zurücksetzen",
            .providerCodex: "Codex",
            .providerClaude: "Claude Code",
            .providerCopilot: "GitHub Copilot",
            .enabled: "Aktiviert",
            .percentageShown: "Angezeigter Prozentwert",
            .usageLimitFiveHourCodexSpark: "GPT-5.3-Codex-Spark-Nutzungslimit für 5 Stunden",
            .usageLimitWeeklyCodexSpark: "Wöchentliches GPT-5.3-Codex-Spark-Nutzungslimit",
            .usageLimitFiveHour: "Nutzungslimit für 5 Stunden",
            .usageLimitWeekly: "Wöchentliches Nutzungslimit",
            .usageLimitSevenDay: "Nutzungslimit für 7 Tage",
            .usageLimitMonthly: "Monatliches Nutzungslimit",
            .usageMetricCredits: "Credits",
            .resetAt: "Zurücksetzen",
            .save: "Sichern",
            .cancel: "Abbrechen",
            .signInToCodex: "Bei Codex anmelden",
            .signInToGitHubCopilot: "Bei GitHub anmelden",
            .copilotToken: "GitHub-Copilot-Token",
            .fetchFailed: "Abruf fehlgeschlagen",
            .signedOut: "Abgemeldet",
            .connected: "Verbunden",
            .accountsSection: "Accounts",
            .codexSessionHelp: "Codex verwendet deine lokale Codex-Anmeldung aus `~/.codex/auth.json`. Wenn du die Desktop-App nutzt, melde dich dort an und aktualisiere. Für Codex CLI führe `codex login` im Terminal aus.",
            .codexCliConnected: "Lokale Codex-Authentifizierung erkannt. Melde dich über Codex ab, wenn du sie trennen möchtest.",
            .claudeSessionHelp: "Claude Code verwendet die lokale Claude-Code-Anmeldung aus Keychain oder `~/.claude/.credentials.json`. Führe `claude` im Terminal aus und aktualisiere danach.",
            .claudeCliConnected: "Lokale Claude-Code-Authentifizierung erkannt. Melde dich über Claude Code ab, wenn du sie trennen möchtest.",
            .copilotPatHelp: "GitHub Copilot meldet sich über den GitHub-Gerätefluss an und lädt die Nutzung aus GitHubs Copilot-API.",
            .copilotDeviceFlowWaiting: "Fahre im Browser fort und gib diesen GitHub-Code ein: %@",
            .copilotDeviceFlowConnected: "GitHub Copilot ist verbunden.",
            .saveAndRefresh: "Sichern und aktualisieren",
            .reload: "Neu laden",
            .tokenSaved: "Token im Schlüsselbund gesichert.",
            .openCodexAndSignIn: "Öffne Codex und melde dich an, klicke dann auf Sitzung sichern.",
            .openGitHubCopilotAndSignIn: "Öffne GitHub, melde dich bei Bedarf an und klicke dann auf Sitzung sichern.",
            .settingsTabAccounts: "Accounts",
            .settingsTabDisplay: "Darstellung",
            .settingsTabNotifications: "Mitteilungen",
            .settingsTabLogs: "Protokolle",
            .settingsTabAbout: "Info",
            .providerStatusOk: "Verbunden",
            .providerStatusNeedsAttention: "Benötigt Aufmerksamkeit",
            .saveSession: "Sitzung sichern",
            .copilotPlanHelp: "Melde dich mit GitHub an, um deine GitHub-Copilot-Nutzung zu laden.",
            .copilotConnectedHelp: "GitHub Copilot ist verbunden. Melde dich ab, um den gesicherten GitHub-Token zu entfernen.",
            .notificationsAheadDescription: "Warnt, wenn ein Kontingent schneller verbraucht wird, als es die Zeitspanne nahelegt.",
            .notificationsBehindDescription: "Warnt, wenn das verbleibende Kontingent deutlich höher ist als für den aktuellen Zeitpunkt der Zeitspanne erwartet.",
            .notificationsCodexResetDescription: "Warnt, wenn das 5-Stunden- oder Wochenfenster von Codex früher zurückgesetzt zu werden scheint als zuvor beobachtet.",
            .notificationsClaudeResetDescription: "Warnt, wenn das 5-Stunden- oder Wochenfenster von Claude Code früher zurückgesetzt zu werden scheint als zuvor beobachtet.",
            .notificationTitleAheadFormat: "Dem Zeitplan voraus: %@",
            .notificationTitleBehindFormat: "Hinter dem Zeitplan: %@",
            .notificationBodyScheduleFormat: "Es verbleiben %d%% Nutzung, während der Zeitplan etwa %d%% erwarten lässt.",
            .notificationTitleCodexReset: "Frühes Codex-Zurücksetzen erkannt",
            .notificationTitleClaudeReset: "Frühes Claude-Code-Zurücksetzen erkannt",
            .notificationBodyResetFormat: "%@ scheint früher als erwartet zurückgesetzt worden zu sein.",
            .notificationMetricFiveHourFormat: "%@ 5-Stunden-Fenster",
            .notificationMetricWeeklyFormat: "%@ Wochenfenster",
            .notificationMetricMonthlyFormat: "%@ Monatskontingent",
            .notificationMetricCreditsFormat: "%@ Credits",
            .copyLogs: "Protokolle kopieren",
            .clearLogs: "Protokolle löschen",
            .noLogs: "Noch keine Protokolle",
            .logsCopied: "Protokolle in die Zwischenablage kopiert.",
            .appVersion: "Version",
            .projectSection: "Projekt",
            .projectRepository: "GitHub-Repository",
            .reportIssue: "Problem melden",
            .legalSection: "Rechtliches",
            .logoDisclaimer: "Das OpenAI-Logo, das Claude-Logo und das GitHub-Copilot-Logo werden nur verwendet, um die jeweiligen Dienste zu identifizieren. Alle Marken, Dienstleistungsmarken und Logos sind Eigentum ihrer jeweiligen Inhaber. Diese App ist unabhängig und weder mit OpenAI, Anthropic oder GitHub verbunden noch von ihnen unterstützt oder gesponsert.",
            .quitApp: "Beenden",
            .menuActionRefresh: "Aktualisieren",
            .menuActionSettings: "Einstellungen",
            .signOut: "Abmelden",
            .noGitHubCopilotSessionFound: "Es wurden noch keine GitHub-Sitzungscookies gefunden.",
            .noCodexSessionFound: "Es wurden noch keine ChatGPT-Sitzungscookies gefunden.",
            .internetConnectionOffline: "Die Internetverbindung scheint offline zu sein.",
        ]
}
